---
title: Lecture XXXX - Note    # e.g., Lecture 10 - Note
subtitle: SOME TOPICS  # e.g., Aesthetic Mappings; Facets; Geometric Objects 
author: 
  - name: YOUR NAME   # e.g., Byeong-Hak Choe
date: last-modified   # e.g., 2024-02-29

execute: 
  echo: true        # true false
  eval: true        # true false
  warning: false    # true false
  message: false    # true false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true                # true false
    number-sections: true    # true false
    code-fold: false         # true false show   # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true         # true false
    highlight-style: a11y          # a11y arrow ayu atom-one breeze github gruvbox tango espresso
                                   # pygments tango espresso espresso zenburn kate nord
                                   # https://quarto.org/docs/output-formats/html-code.html#highlighting
---


```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(hrbrthemes)
library(DT)
library(rmarkdown)

```

##Lecture 22
###Classwork 10 cont.
####Q2g
```{r}
korea <- gapminder |> 
  filter(str_detect(country, "Korea"))
```

#Summarize()
```{r}
df <- data_frame(x = c(1:10))
df_sum <- df |> 
  mutate(x_mean = mean(x),
            x_sd = sd(x),
            x_min = min(x),
            x_median = median(x),
            x_q1 = quantile(x, prob = .75),
            x_max = max(x))
```

```{r}
df <- data.frame(
  group = c("A", "B", "A", "B"),
  score = c(50, 65, 70, 85)
)

df |> 
  group_by(group) |> 
  summarize(mean_val = mean(score))
```

```{r}
library(nycflights13)

df_dep_delay <- flights |> 
  summarize(dep_delay_mean = mean(dep_delay),
            dep_delay_mean_rmNA = mean(dep_delay, na.rm = T))
```

```{r}
by_day <- flights |> 
  group_by(year, month, day) |> 
  summarise(delay = mean(dep_delay, na.rm = T)) |> 
  arrange(-delay)
```

##n()
```{r}
df <- data.frame(
  group = c("A", "B", "A", "B", "A"),
  score = c(50, 65, 70, 85, NA) )

df_sum <- df |> 
  group_by(group) |> 
  summarize(
    mean_val = mean(score, na.rm = T),
    n = n() )
```

##Classwork 11 
###Q1a
```{r}
nyc_dogs <- read_csv('https://bcdanl.github.io/data/nyc_dogs_cleaned.csv')

q1a <- nyc_dogs |> 
  group_by(breed) |> 
  summarise(n = n()) |> 
  arrange(-n)
```

##Q1b
```{r}
q1a_top5 <- q1a |> 
  filter(!is.na(breed)) |> 
  mutate(ranking = dense_rank(-n)) |> 
  filter(ranking <= 5)
```
