---
title: Lecture XXXX - Note    # e.g., Lecture 10 - Note
subtitle: SOME TOPICS  # e.g., Aesthetic Mappings; Facets; Geometric Objects 
author: 
  - name: YOUR NAME   # e.g., Byeong-Hak Choe
date: last-modified   # e.g., 2024-02-29

execute: 
  echo: true        # true false
  eval: true        # true false
  warning: false    # true false
  message: false    # true false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true                # true false
    number-sections: true    # true false
    code-fold: false         # true false show   # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true         # true false
    highlight-style: a11y          # a11y arrow ayu atom-one breeze github gruvbox tango espresso
                                   # pygments tango espresso espresso zenburn kate nord
                                   # https://quarto.org/docs/output-formats/html-code.html#highlighting
---


```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(hrbrthemes)
library(DT)
library(rmarkdown)

```

# Aesthetic Mappings

- An aesthetic is a visual property (e.g., size, shape, color) of the objects (e.g., class) in our plot.
  - We can display a point in different ways by changing the values of its aesthetic properties.


```{r}
ggplot(data = mpg) + 
  geom_point(mapping = 
               aes(x = displ, 
                   y = hwy, 
                   color = class) )
```


```{r}

```

## Overplotting Issues

```{r}

```


## Section 2

```{r}

```



```{r}

```


