---
title: Lecture XXXX - Note    # e.g., Lecture 10 - Note
subtitle: SOME TOPICS  # e.g., Aesthetic Mappings; Facets; Geometric Objects 
author: 
  - name: YOUR NAME   # e.g., Byeong-Hak Choe
date: last-modified   # e.g., 2024-02-29

execute: 
  echo: true        # true false
  eval: true        # true false
  warning: false    # true false
  message: false    # true false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true                # true false
    number-sections: true    # true false
    code-fold: false         # true false show   # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true         # true false
    highlight-style: a11y          # a11y arrow ayu atom-one breeze github gruvbox tango espresso
                                   # pygments tango espresso espresso zenburn kate nord
                                   # https://quarto.org/docs/output-formats/html-code.html#highlighting
---


```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(hrbrthemes)
library(DT)
library(rmarkdown)

```

##Lecture 23
###Practice
```{r}
library(nycflights13)
```

#ungroup
```{r}
daily <- flights |> 
  group_by(year, month, day)

by_day <- daily |> 
  summarize(flights = n())


```

#Count
```{r}
n_dest <- flights |> 
  count(dest) |> 
  arrange(-n)
```

```{r}
ggplot(diamonds) +
  geom_histogram(aes(x = carat),
                 binwidth = .5)
```

#group_by() with mmultiple variables
```{r}
daily <- flights |> 
  group_by(year, month, day)

per_day <- daily |> 
  summarize(flights = n())

per_month <- per_day |> 
  summarize(flights = sum(flights))

per_year  <- per_month |> 
  summarize(flights = sum(flights))
```

##Classwork 11
###Q1a
```{r}
top_breeds <- nyc_dogs |> 
  count(breed) |> 
  arrange(-n) |> 
  filter(!is.na(breed)) |> 
  slice_head(n = 5)
```

###Q1b
```{r}
only_top_5 <- nyc_dogs |> 
  filter(breed == "yorkshire terrier" |
           breed == "shih tzu" |
           breed == "chihuahua" |
           breed == "labrador" |
           breed == "pit bull")
```

```{r}

ggplot(only_top_5, aes(y = breed)) +
  geom_bar() +
  facet_wrap(borough ~ .)
```
#Q1c
```{r}
q1c <- nyc_dogs |> 
  group_by(borough) |> 
  count(breed) |> 
  arrange(borough, -n) |> 
  filter(!is.na(breed)) |> 
  slice_max(n, n = 5)
```

#Q1d
```{r}
q1d <- nyc_dogs |> 
  group_by(gender) |> 
  count(name)
  
```
