---
title: Lecture XXXX - Note    # e.g., Lecture 10 - Note
subtitle: SOME TOPICS  # e.g., Aesthetic Mappings; Facets; Geometric Objects 
author: 
  - name: YOUR NAME   # e.g., Byeong-Hak Choe
date: last-modified   # e.g., 2024-02-29

execute: 
  echo: true        # true false
  eval: true        # true false
  warning: false    # true false
  message: false    # true false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true                # true false
    number-sections: true    # true false
    code-fold: false         # true false show   # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true         # true false
    highlight-style: a11y          # a11y arrow ayu atom-one breeze github gruvbox tango espresso
                                   # pygments tango espresso espresso zenburn kate nord
                                   # https://quarto.org/docs/output-formats/html-code.html#highlighting
---


```{r setup}
#| include: false
library(tidyverse)
library(skimr)
library(hrbrthemes)
library(DT)
library(rmarkdown)

```

#Lecture 24
##Class work 11 cont.
###Q1e

Find the five most popular dog 'name's for each 'gender' in each 'borough'.

```{r}
q1e <- nyc_dogs |> 
  count(borough, gender, name) |> 
  group_by(borough, gender) |> 
  slice_max(n, n = 5) |> 
  filter(!is.na(name)) |> 
  filter(!is.na(gender))
```

#Q1f
```{r}
nyc_dogs <- nyc_dogs |> 
  mutate(age = 2024 - birth_year)

ggplot(nyc_dogs, aes(x = age)) +
  geom_histogram()
```







